version: "3"
services:
  app:
    container_name: web-ctf
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      frontend_default:
    ports:
      - "3000:3000"

networks:
  frontend_default:
    external: true